const salaryModel = require("./models/salaryModel");
const { create } = require("./models/userModel");

module.exports = {
  crmDashboard: 'crm_dashboard',
  leadDashboard: 'lead_dashboard',
  createUser: 'create_user',
  readUser: 'read_user',
  updateUser: 'update_user',
  viewUser: 'view_user',
  deleteUser: 'delete_user',
  resignUser: 'resign_user',
  blockUser: 'block_user',
  resetPassword: 'reset_password',
  restoreResignedUser: 'restore_resigned_user',
  createLead: 'create_lead',
  viewLead: 'view_lead',
  editLead: 'edit_lead',
  deleteLead: 'delete_lead',
  updateproductstage: 'update_product_stage',
  moveLead: 'move_lead',
  unassignedLead: 'unassigned_lead',
  rejectLead: 'reject_lead',
  transferLead: 'transfer_lead',
  addUserLead: 'add_user_lead',
  removeUserLead: 'remove_user_lead',
  convertLead: 'convert_lead',
  addlabels: 'add_labels',
  adduser: 'add_user',
  deleteuser: 'delete_user',
  fileupload: 'file_upload',
  filedelete: 'file_delete',
  filedownload: 'file_download',
  showphonebook: 'show_phonebook',
  fileuploadforphonebook: 'file_upload_for_phonebook',
  createcontract: 'create_contract',
  viewcontract: 'view_contract',
  editcontract: 'edit_contract',
  rejectcontract: 'reject_contract',
  updateproductstagecontract: 'update_product_stage_contract',
  deletecontract: 'delete_contract',
  createdeal: 'create_deal',
  viewdeal: 'view_deal',
  viewdealforaccountant: 'view_deal_for_accountant',
  editdeal: 'edit_deal',
  rejectdeal: 'reject_deal',
  restoredeal:'restore_deal',
  updatedealstage: 'update_deal_stage',
  appmanagement: 'app_management',
  labelmanagement: 'label_management',
  accountantmanagement: 'accountant_management',
  hrmanagement: 'hr_management',
  hrDashboard: 'hr_dashboard',
  shiftmanagement: 'shift_management',
  deparmentmanagement: 'department_management',
  holidaymanagement: 'holiday_management',
  attendancemanagement: 'attendance_management',
  areamanagement: 'area_management',
  leavemanagement: 'leave_management',
  /////
  generatepenality: 'generate_penalty',
  viewpenality: 'view_penalty',
  editpenality: 'edit_penalty', 
  createpenality: 'create_penalty',
  approvepenality: 'approve_penalty',
  salarymanagement: 'salary_management',
  createsalary: 'create_salary',
  Adjustsalary: 'adjust_salary',
  editsalary: 'edit_salary',
  viewsalary: 'view_salary',
  bouncemanagement: 'bounce_management',
  payrollmanagement: 'payroll_management',
  unapprovedpayroll: 'unapproved_payroll',
  payroll_approval: 'payroll_approval',
  unpaidpayroll: 'unpaid_payroll',
  geratepayroll: 'generate_payroll',
  viewpayroll: 'view_payroll',
  payrollhistory: 'payroll_history',
  payrollpayement: 'payroll_payment',
  advance_management: 'advance_management',
  advance_approval: 'advance_approval',
  pay_advance_payment: 'pay_advance_payment',
  view_advance_payment: 'view_advance_payment',


  /////
  leave_final_approval: 'leave_final_approval',
  edit_leave: 'edit_leave',
  leave_history: 'leave_history',
  hr_leave_approval: 'hr_leave_approval',
  hr_create_leave: 'hr_create_leave',
  manager_leave_approval: 'manager_leave_approval',

  hr_management_no_lc: 'hr_management_no_lc',
  activity_report: 'activity_report',
};
